stages:
    - build
    #- test
    - build_frontend
    - production_deploy
    - develop_deploy


variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=true"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
    image: gradle:alpine
    stage: build
    script: gradle --build-cache assemble
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - build
            - .gradle
    only:
         - master
         - develop
#test:
#    image: gradle:alpine
#    stage: test
#    script:
#        - gradle check
#    cache:
#        key: "$CI_COMMIT_REF_NAME"
#        policy: pull
#    only:
#        #- develop
#        - master

build_frontend:
    stage: build_frontend
    image: node:latest
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - src/main/webapp
    script:
        - mkdir src/main/webapp
        - mkdir src/main/webapp/WEB-INF/
        - mkdir src/main/webapp/WEB-INF/view/
        - cd frontend
        - npm install
        - npm run build
        - rm -r node_modules
        - cd build
        - mv -v index.html  ../../src/main/webapp/WEB-INF/view/
        - mv -v *  ../../src/main/webapp/
    artifacts:
        untracked: true
    only:
        - master
        - develop

production_deploy:
    stage: production_deploy
    image: ruby:latest
    artifacts:
           when: always
    dependencies:
        - build_frontend
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_MASTER --api-key=$HEROKU_API_KEY  --skip_cleanup
    only:
        - master

develop_deploy:
    stage: develop_deploy
    image: ruby:latest
    artifacts:
           when: always
    dependencies:
        - build_frontend
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_DEVELOP --api-key=$HEROKU_API_KEY  --skip_cleanup
    only:
        - develop