stages:
    - build
    - test
    - deploy

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
    image: gradle:alpine
    stage: build
    script: gradle --build-cache assemble
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - build
            - .gradle
    only:
         - 12_ci_cd
test:
    image: gradle:alpine
    stage: test
    script: gradle check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - gradle test --tests GroupControllerTest
            - gradle test --tests PeriodControllerTest
            - gradle test --tests RoomControllerTest
            - gradle test --tests SubjectControllerTest
            - gradle test --tests TeacherControllerTest
    only:
         - 12_ci_cd
deploy:
    stage: deploy
    image: ruby:latest
    artifacts:
           when: always
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        #- dpl --provider=heroku --app=$HEROKU_APP_MASTER --api-key=$HEROKU_API_KEY
    only:
        - 12_ci_cd