version: '3.5'

services:
  schedule-app:
    container_name: schedule-app
    restart: always
    image: "${SCHEDULE_APP_IMAGE}"
    ports:
      - "${SCHEDULE_APP_PORT}:8080"
    environment:
      - POSTGRES_URL
      - POSTGRES_ADMIN
      - POSTGRES_ADMIN_PASSWORD
      - REDIS_URL
      - MONGO_DATABASE
      - MONGO_URL
      - JWT_TOKEN
      - JWT_EXPIRED
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - backend
    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "curl --output /dev/null --silent --fail http://127.0.0.1:8080/public/semesters || exit 1"
          ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s  

  postgres:
    extends:
      file: docker-compose-deps.yml
      service: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_ADMIN
      - POSTGRES_ADMIN_PASSWORD
      - POSTGRES_DATABASE
