#!/bin/bash

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" << EOSQL
    CREATE USER $POSTGRES_ADMIN_USERNAME WITH PASSWORD '$POSTGRES_ADMIN_PASSWORD';
    CREATE DATABASE $POSTGRES_DATABASE OWNER $POSTGRES_ADMIN_USERNAME;
    CREATE DATABASE $POSTGRES_TEST_DATABASE OWNER $POSTGRES_ADMIN_USERNAME;
EOSQL

psql --set ON_ERROR_STOP=off -U "$POSTGRES_ADMIN_USERNAME" -d "$POSTGRES_DATABASE" -f "/docker-entrypoint-initdb.d/initial_data.dump"
