name: Build and Push Schedule Docker Images

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push [Production Version]
        uses: docker/build-push-action@v5
        with:
          push: true
          target: backend-tomcat-prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/schedule-app:${{ github.sha }},
            ${{ secrets.DOCKERHUB_USERNAME }}/schedule-app:latest
      
      - name: Build and push [Test Version]
        uses: docker/build-push-action@v5
        with:
          push: true
          target: backend-test
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/schedule-test-app:${{ github.sha }},
            ${{ secrets.DOCKERHUB_USERNAME }}/schedule-test-app:latest
